# Amazon Linux docker image to build a Lambda package with a compiled dependency
# https://docs.aws.amazon.com/lambda/latest/dg/current-supported-versions.html

FROM public.ecr.aws/sam/build-python3.9

WORKDIR /root

COPY . .
